# Generated by Django 3.2.9 on 2021-11-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='med_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.medico'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='pac_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.paciente'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='esp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.especialidades'),
        ),
    ]
