# Generated by Django 3.2.9 on 2021-12-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20211124_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='cit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='esp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pac_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
