# Generated by Django 3.2.9 on 2021-12-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_medico_med_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='pac_cell_telf',
            field=models.CharField(max_length=13),
        ),
    ]
